### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by lonelysoul** [NueXini/NueXini_Packages#2]
find: ‘feeds/NueXini_Packages/luci-app-cpulimit/po/zh-cn/zh_Hans’: Too many levels of symbolic links

**Comment by NueXini** [comment]
It has been fixed it in https://github.com/NueXini/NueXini_Packages/commit/905619fc7045dec9bb4d2b0ae309e4b675692f33
Please compile again with
```bash
./scripts/feeds update -a && ./scripts/feeds install -a
```

**Comment by lonelysoul** [comment]
新版已无此问题
