### ISSUE TITLE
仓库名不符

### ISSUE THREAD

**Issue by catsimple** [NueXini/NueXini_Packages#20]
luci-app-serverchan中的makefile已更名为luci-app-wechatpush
而此仓库下仍为原名，这会导致两个问题：
1.无法使用make package/luci-app-wechatpush/compile V=99命令进行ipk单独编译，因为文件夹名为luci-app-serverchan

2.编译后的luci-app-wechatpush，语言包与主体不符，无法安装
![image](https://github.com/NueXini/NueXini_Packages/assets/23014926/a40ab194-7ec5-4c82-b259-5043ff6f6483)
![image](https://github.com/NueXini/NueXini_Packages/assets/23014926/2792e876-fd68-4b8e-a0d5-841b300d625a)

**Comment by NueXini** [comment]
fix
