### ISSUE TITLE
luci-app-adguardhome执行文件路径有问题

### ISSUE THREAD

**Issue by AlasJiahui** [NueXini/NueXini_Packages#22]
建议把luci-app-adguardhome/root/etc/config/AdGuardHome中的
option binpath '/usr/bin/AdGuardHome/AdGuardHome'
改为
option binpath '/usr/bin/AdGuardHome'

**Comment by NueXini** [comment]
请提供一下详细的log

**Comment by AlasJiahui** [comment]
> 请提供一下详细的log

很明显啊
	option workdir '/usr/bin/AdGuardHome'
	option binpath '/usr/bin/AdGuardHome/AdGuardHome'
这两个地址不一样，导致在/usr/bin/AdGuardHome文件夹里找不到bin文件
