### ISSUE TITLE
Update_NueXini_Packages action报错，导致packages出错，无法编译。

### ISSUE THREAD

**Issue by lonelysoul** [NueXini/NueXini_Packages#4]
![image](https://user-images.githubusercontent.com/62841189/153858206-b8aa84c4-5948-446d-973f-081d399e8558.png)
Run [ -e $README ] && cp -f $README packages
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.

**Comment by lonelysoul** [comment]
![image](https://user-images.githubusercontent.com/62841189/154057662-357a9397-b342-4dbb-99d3-04c17a33fcc0.png)
缺少依赖

**Comment by NueXini** [comment]
按照教程来
```bash
ehco 'src-git NueXini_Packages https://github.com/NueXini/NueXini_Packages.git' >> feeds.conf.default
```

**Comment by lonelysoul** [comment]
第一步，加完这样；
![image](https://user-images.githubusercontent.com/62841189/154264100-7034124b-3a34-4e89-abcd-f1838566a42f.png)
第二步，执行完这样：
![image](https://user-images.githubusercontent.com/62841189/154264348-33b35adb-e54b-4610-b217-5ad75e76d7bd.png)

这次剩下五个依赖缺少：
WARNING: Makefile 'package/feeds/NueXini_Packages/amule/Makefile' has a dependency on 'libwxbase', which does not exist
WARNING: Makefile 'package/feeds/NueXini_Packages/antileech/Makefile' has a dependency on 'libwxbase', which does not exist
WARNING: Makefile 'package/feeds/NueXini_Packages/luci-app-samba/Makefile' has a dependency on 'samba36-server', which does not exist
WARNING: Makefile 'package/feeds/NueXini_Packages/luci-app-vlmcsd/Makefile' has a dependency on 'vlmcsd', which does not exist
WARNING: Makefile 'package/feeds/NueXini_Packages/ntfs3-mount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist

**Comment by NueXini** [comment]
> 第一步，加完这样； ![image](https://user-images.githubusercontent.com/62841189/154264100-7034124b-3a34-4e89-abcd-f1838566a42f.png) 第二步，执行完这样： ![image](https://user-images.githubusercontent.com/62841189/154264348-33b35adb-e54b-4610-b217-5ad75e76d7bd.png)
> 
> 这次剩下五个依赖缺少： WARNING: Makefile 'package/feeds/NueXini_Packages/amule/Makefile' has a dependency on 'libwxbase', which does not exist WARNING: Makefile 'package/feeds/NueXini_Packages/antileech/Makefile' has a dependency on 'libwxbase', which does not exist WARNING: Makefile 'package/feeds/NueXini_Packages/luci-app-samba/Makefile' has a dependency on 'samba36-server', which does not exist WARNING: Makefile 'package/feeds/NueXini_Packages/luci-app-vlmcsd/Makefile' has a dependency on 'vlmcsd', which does not exist WARNING: Makefile 'package/feeds/NueXini_Packages/ntfs3-mount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist

这些不是错误,并不影响
