### ISSUE TITLE
缺少两个依赖

### ISSUE THREAD

**Issue by shookgao** [NueXini/NueXini_Packages#6]
在`./scripts/feeds update -a && ./scripts/feeds install -a`的时候会提示：
>WARNING: Makefile 'package/feeds/NueXini_Packages/baidupcs-web/Makefile' has a build dependency on 'go-rice/host', which does not exist
WARNING: Makefile 'package/feeds/NueXini_Packages/ntfs3-mount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist

然后`make menuconfig`的时候也会提示

**Comment by NueXini** [comment]
fixed
https://github.com/NueXini/NueXini_Packages/commit/a6245e991df3bd710c8f2f56d41191128629b5f9
