### ISSUE TITLE
cpolar-stable-linux-amd64地址好像改了 

### ISSUE THREAD

**Issue by gzsdbb** [NueXini/NueXini_Packages#7]
make download 会出错,后缀好像改zip了

**Comment by NueXini** [comment]
没有问题，自己检查网络环境

**Comment by gzsdbb** [comment]
网络应该没问题吧
https://static.cpolar.com/downloads/releases/3.2.86.16/cpolar-stable-linux-amd64.tar.xz确定不能下载了
但https://static.cpolar.com/downloads/releases/3.2.86.16/cpolar-stable-linux-amd64.zip能

**Comment by NueXini** [comment]
哪里有你说的下载链接，`make clean`先吧
https://github.com/NueXini/NueXini_Packages/blob/35a2aded722be4b63eb538941bd4d939604050dd/cpolar/Makefile#L54
